name: Android
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_apps/nviti-demo-app-flutter
    steps:
      - uses: actions/checkout@v4
        with:
          path: demo_apps/nviti-demo-app-flutter
      - uses: actions/checkout@v4
        with:
          repository: pamekar/nviti-chat-flutter
          path: sdks/nviti-chat-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug
